### PR TITLE
bump-gems-2018-04-28

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by greysteil** [comment]
Would you be up for creating dependency update PRs? I built [Dependabot](https://dependabot.com) to do that, and it's totally free for open source. Just trying to get a few more people using it. :octocat:

**Comment by mensfeld** [comment]
@greysteil thanks but we already use Coditsu to notify us about our outdated dependencies.

**Comment by greysteil** [comment]
Oh cool, hasn’t seen it before but they look great!

**Comment by greysteil** [comment]
Also realise I left out the most important thing about Dependabot in the above comment (now edited) which is that it creates the PRs for you rather than creating alerts. Appreciate you might not want more dependency management tools in your life, though!

**Pull request merged**
