### PR TITLE
Dependency cleanup and support for new API endpoints

### PR DESCRIPTION
**Pull request by brissmyr**

### CODE REVIEW

**Comment by brissmyr** [comment]
@filiptepper I remove the `do_not_track` in the process. Should I put it back?

**Comment by filiptepper** [comment]
@brissmyr I believe we ended up not using this feature at all.

**Comment by wallin** [comment]
What's left until we can release this? Identify?

**Comment by brissmyr** [comment]
Yeah, might as well add `identify` right away. As well as update website docs.

**Comment by brissmyr** [comment]
There we go

**Pull request merged**
