### PR TITLE
require ruby version >= 2.2.6

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by stevenou** [comment]
this is a breaking change as far as i can tell. should note it in the changelog + probably should bump major version?

**Comment by mensfeld** [comment]
@stevenou support for ruby 2.1 has ended quite while ago: https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/ - not quite sure if it is that much of a breaking change in that case as this ruby versions shouldn't be used at all...

**Comment by nijikon** [comment]
@stevenou And just to add to what @mensfeld wrote, support for `2.2` will end at the end of March 2018. We will be dropping support for it since the beginning of April. https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-2-9-released/

**Comment by stevenou** [comment]
i understand that. i'm arguing this is a breaking change and should be noted as such. though i now see there is huge amounts of debate about whether a dependency change should constitute a major version bump or not.

**Pull request merged**
