### PR TITLE
drop auto-detection of ruby framework - go with the manual setup

### PR DESCRIPTION
**Pull request by bartes**

### CODE REVIEW

**Comment by bartes** [comment]
we can add it to release note draft after merge and publish there. will that be enough ?

**Comment by bartes** [comment]
@nijikon - added changelog here https://github.com/castle/castle-ruby/pull/36

**Comment by nijikon** [comment]
When #36 is merged, please add a proper changelog message for this PR.

**Comment by bartes** [comment]
@nijikon done

**Pull request merged**
