### PR TITLE
Use Latest Dependencies

### PR DESCRIPTION
**Pull request by marcqualie**
This should fix the failing tests, use the latest dependencies and also a few basic tests to ensure each model correctly extends the `Castle::Model` class and verify test runner is running correctly on Travis.

[Build Status](https://travis-ci.org/givey/castle-ruby)

### CODE REVIEW

**Comment by brissmyr** [comment]
Cool, thanks! Just a note on https://github.com/givey/castle-ruby/commit/0971d8b72361acf1f3fb15d101eaaea6d4da9b1c, this will probably raise warnings about unspecified versions when building the gem. Not sure about the preferred way of doing proper versioning, what's your view on it @marcqualie?

**Comment by marcqualie** [comment]
Yeah I'm not a fan of it either to be honest. The best way (assuming all the gems use semantic versioning) is to lock them to their major versions with `~> 4.0` for example. This would allow them to be easily updated with hopefully no breaking changes. I'll make the change and re-push.

**Comment by marcqualie** [comment]
@brissmyr the gems are now locked to their latest major versions. Having a service like [versioneye](https://www.versioneye.com/) or [gemnasium](https://gemnasium.com/) track the gemspec file will make it easy to keep on top of updates within this criteria for security patches and new releases.

**Comment by brissmyr** [comment]
Perfect! Gemnasium is actually in there already.

**Pull request merged**
